'use client'

export const dynamic = 'force-dynamic'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import type { Session, User } from '@supabase/supabase-js'
import { Camera, FileText, Film, Heart, ImagePlus, LogOut, Plus, Save, ShieldCheck, Sparkles, Users } from 'lucide-react'

const sections = [
  { key: 'photos', label: 'Photos', icon: Camera, table: 'photos' }, { key: 'milestones', label: 'Milestones', icon: Sparkles, table: 'milestones' }, { key: 'letters', label: 'Letters', icon: FileText, table: 'letters' }, { key: 'family', label: 'Family', icon: Users, table: 'family_members' }, { key: 'videos', label: 'Videos', icon: Film, table: 'videos' }, { key: 'birthday', label: 'Birthday', icon: Heart, table: 'birthday' }, { key: 'funny', label: 'Funny memories', icon: Sparkles, table: 'funny_memories' }, { key: 'timeline', label: 'Timeline', icon: ImagePlus, table: 'chapters' },
]

export default function AdminPage() {
  const supabase = createClient(); const [user, setUser] = useState<User | null>(null); const [authorized, setAuthorized] = useState(false); const [loading, setLoading] = useState(true); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [active, setActive] = useState(sections[0]); const [rows, setRows] = useState<any[]>([]); const [saving, setSaving] = useState(false); const [editingId, setEditingId] = useState<string | null>(null)
  useEffect(() => { supabase.auth.getUser().then(async ({ data }: { data: { user: User | null } }) => { setUser(data.user); if (data.user) { const { data: admin } = await supabase.from('admin_users').select('user_id').eq('user_id', data.user.id).maybeSingle(); setAuthorized(Boolean(admin)) } setLoading(false) }); const { data } = supabase.auth.onAuthStateChange((_event: string, session: Session | null) => { setUser(session?.user ?? null); if (!session?.user) setAuthorized(false) }); return () => data.subscription.unsubscribe() }, [supabase])
  useEffect(() => { if (!user) return; supabase.from(active.table).select('*').limit(20).then(({ data }: { data: any[] | null }) => setRows(data ?? [])) }, [user, active, supabase])
  async function signIn(e: React.FormEvent) { e.preventDefault(); setError(''); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) setError('Invalid email or password.') }
  async function addPlaceholder() { setSaving(true); const payload = active.key === 'milestones' ? { title: 'New milestone', description: '', sort_order: rows.length } : active.key === 'letters' ? { author: 'Family', title: 'A letter to you', message: '', published: false, sort_order: rows.length } : active.key === 'family' ? { name: 'New family member', relationship: 'Family', published: false, sort_order: rows.length } : active.key === 'chapters' ? { age: rows.length + 1, year: 2025 + rows.length + 1, title: `Age ${rows.length + 1}`, status: 'locked' } : { title: 'New memory', caption: '', published: false, sort_order: rows.length }; const { data, error } = await supabase.from(active.table).insert(payload).select().single(); if (!error && data) setRows([...rows, data]); setSaving(false) }
  async function saveRow(row: any) { setSaving(true); const { error } = await supabase.from(active.table).update({ title: row.title, name: row.name, caption: row.caption, description: row.description, message: row.message, relationship: row.relationship, published: row.published, updated_at: new Date().toISOString() }).eq('id', row.id); if (error) setError('Unable to save this memory.'); else setEditingId(null); setSaving(false) }
  if (loading) return <main className="admin-gate"><div className="admin-login"><span className="eyebrow">Loading memory book</span><h1>Opening the archive...</h1></div></main>
  if (!user) return <main className="admin-gate"><form onSubmit={signIn} className="admin-login"><ShieldCheck size={32} /><span className="eyebrow">Private family archive</span><h1>Open the memory book</h1><p>Sign in with an authorized family account to keep the story growing.</p><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label><button type="submit">Sign in</button>{error && <small>{error}</small>}</form></main>
  if (user && !authorized) return <main className="admin-gate"><div className="admin-login"><ShieldCheck size={32} /><span className="eyebrow">Private family archive</span><h1>Access is restricted</h1><p>This account is signed in, but it has not been added to the family archive.</p><button type="button" onClick={() => supabase.auth.signOut()}>Sign out</button></div></main>
  return <main className="admin-shell"><header className="admin-header"><div><span className="eyebrow">Raghav&apos;s time capsule</span><h1>Memory book editor</h1></div><button className="admin-logout" onClick={() => supabase.auth.signOut()}><LogOut size={16} /> Sign out</button></header><div className="admin-layout"><aside className="admin-sidebar"><p>Manage</p>{sections.map(item => { const Icon = item.icon; return <button className={active.key === item.key ? 'selected' : ''} key={item.key} onClick={() => setActive(item)}><Icon size={16} />{item.label}</button> })}</aside><section className="admin-content"><div className="admin-toolbar"><div><span className="eyebrow">{active.label}</span><h2>Keep the story growing</h2></div><button onClick={addPlaceholder} disabled={saving}><Plus size={16} /> Add memory</button></div><div className="admin-list">{rows.length ? rows.map(row => <article key={row.id}>{editingId === row.id ? <div className="admin-edit-form"><input aria-label="Title" value={row.title || row.name || row.caption || ''} onChange={e => setRows(rows.map(item => item.id === row.id ? { ...item, [row.title !== undefined ? 'title' : row.name !== undefined ? 'name' : 'caption']: e.target.value } : item))} /><textarea aria-label="Description" value={row.description || row.message || row.relationship || ''} onChange={e => setRows(rows.map(item => item.id === row.id ? { ...item, [row.message !== undefined ? 'message' : row.description !== undefined ? 'description' : 'relationship']: e.target.value } : item))} /><div><button onClick={() => saveRow(row)} disabled={saving}><Save size={15} /> Save</button><button onClick={() => setEditingId(null)}>Cancel</button></div></div> : <><div><b>{row.title || row.name || row.caption || `Age ${row.age}` || 'Memory'}</b><small>{row.description || row.relationship || row.message || row.status || 'Ready to edit'}</small></div><button aria-label="Edit memory" onClick={() => setEditingId(row.id)}><Save size={15} /></button></>}</article>) : <div className="empty-admin"><Sparkles size={25} /><h3>This chapter is waiting to be written.</h3><p>Add the first {active.label.toLowerCase()} memory to begin.</p><button onClick={addPlaceholder}><Plus size={15} /> Add memory</button></div>}</div></section></div></main>
}
